AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 20
    Runtime: java21
    MemorySize: 512
    Architectures:
      - x86_64
Resources:
  PatientCallPopulatorFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: patient-call-populator
      Handler: telran.pma.PatientCallPopulator::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt PatientCallStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  PatientCallStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: patient-calls
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  SavedPatientCallStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: saved-patient-calls
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  PatientDataProviderFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: patient-data-provider
      Handler: telran.pma.AppPatientDataProvider::handleRequest
      Environment:
        Variables:
          DB_PASSWORD: 123456.com
      Events:
        PatientDataProvider:
          Type: Api
          Properties:
            Path: /patients
            Method: get

Outputs:
  PatientDataProviderApi:
    Description: "API Gateway endpoint URL for Prod stage for PatientDataProvider function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/patients/"