AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 20
    Runtime: java21
    MemorySize: 512
    Architectures:
      - x86_64
Resources:
  PatientCallPopulatorFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: patient-call-populator
      Handler: telran.pma.PatientCallPopulator::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt PatientCallStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  ApprovalPopulatorFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: approval-populator
      Handler: telran.pma.ApprovalPopulator::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt ApprovalStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  RejectPopulatorFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: reject-populator
      Handler: telran.pma.RejectPopulator::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt RejectStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  TreatmentProtocolFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: treatment-protocol-function
      Handler: telran.pma.AppRecommendationProvider::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          PATIENT_DATA_PROVIDER_CLASS_NAME: "telran.pma.PatientDataHttpClient"
          PATIENT_DATA_URL: !Sub "http://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/patients/"
          S3_CLIENT_CLASS_NAME: "telran.pma.S3JsonClient"
          LOGGER_LEVEL: finest
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt SavedPatientCallStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  NotificationSenderFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: notification-sender
      Handler: telran.pma.AppEmailNotifier::handleRequest
      Policies: 
        - Statement:
            Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
      Environment:
        Variables:
          LOGGER_LEVEL: finest
          EMAIL_SENDER_CLASS_NAME: "telran.pma.MailSenderSes"
          DB_PASSWORD: 123456.com
      Events: 
        DynamoDbItemInsert:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            BatchSize: 1
            Stream: !GetAtt NotificationStream.StreamArn
            FilterCriteria:
              Filters:
                - Pattern: '{"eventName": ["INSERT"]}'
  ApprovalStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: patient-approvals
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  RejectStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: patient-rejects
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  PatientCallStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: patient-calls
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  SavedPatientCallStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: saved-patient-calls
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  NotificationStream:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: notifications
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: message
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: message
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  PatientDataProviderFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: patient-data-provider
      Handler: telran.pma.AppPatientDataProvider::handleRequest
      Environment:
        Variables:
          DB_PASSWORD: 123456.com
      Events:
        PatientDataProvider:
          Type: Api
          Properties:
            Path: /patients
            Method: get
  SchedulerRejectFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: scheduler-reject-function
      Handler: telran.pma.AppRejectProvider::handleRequest
      Environment:
        Variables:
          DB_PASSWORD: 123456.com
          STREAM_NAME: patient-rejects
          STREAM_CLASS_NAME: telran.pma.DynamoDbStreamRejectData
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
  SchedulerNotificationFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: scheduler-notification-function
      Handler: telran.pma.AppNotificationProvider::handleRequest
      Environment:
        Variables:
          DB_PASSWORD: 123456.com
          STREAM_NAME: notifications
          STREAM_CLASS_NAME: telran.pma.DynamoDbStreamNotificationData
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

Outputs:
  PatientDataProviderApi:
    Description: "API Gateway endpoint URL for Prod stage for PatientDataProvider function"
    Value: !Sub "http://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/patients/"