name: Build and Deploy patient-call-receiver

on:
  push:
    # Запускать только если изменился patient-call-receiver или сам workflow
    paths:
      - 'patient-call-receiver/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build all modules
        run: mvn clean install -DskipTests

      - name: Build JAR
        working-directory: patient-call-receiver
        run: mvn clean package -DskipTests

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "patient-call-receiver/target/patient-call-receiver-1.0-SNAPSHOT.jar,patient-call-receiver/Dockerfile"
          target: "/home/ec2-user/patient-call-receiver-deploy"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/patient-call-receiver-deploy
            docker build -t patient-call-receiver .
            docker stop patient-call-receiver || true
            docker rm patient-call-receiver || true
            docker run -d --name patient-call-receiver -p 5500:5500 patient-call-receiver